version: "3.8"

services:
  frontend:
    build: .
    container_name: react-app

    ports:
      - "3000:5173"

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      NODE_ENV: development
      VITE_HOST: 0.0.0.0
      VITE_PORT: 5173

    restart: unless-stopped
